#!/bin/bash

set -euo pipefail

go build cmd/dependabot/dependabot.go

# To get a clear signal we're not cloning, using a repo with no dependencies.
git clone https://github.com/golang/sys tmp/sys
trap 'rm -rf tmp/sys' EXIT

./dependabot update go_modules golang/sys --local tmp/sys 2>&1 | tee tmp/output

# verify the repo was not cloned
if grep -q "https://github.com:443/golang/sys/git-upload-pack" tmp/output; then
  echo "FAIL: repo was cloned"
  export FAIL=1
fi

# Next, test using a repo that isn't a Git repository.
rm -rf tmp/sys/.git

./dependabot update go_modules golang/sys --local tmp/sys 2>&1 | tee tmp/output

# verify the repo was not cloned
if grep -q "https://github.com:443/golang/sys/git-upload-pack" tmp/output; then
  echo "FAIL: repo was cloned"
  export FAIL=1
fi

if [ -n "${FAIL:-}" ]; then
  exit 1
fi
